language: java
jdk:
  - openjdk13
#cache:
#  directories:
#    these take as long to download from the cache as from the original source
#  - $HOME/.m2
install:
  - mvn install -Dgwt.validateOnly -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  #- apk add graphviz
script:
  - mvn clean test -B -V -Duser.timezone=CET
  - mvn clean install -Dgwt.validateOnly -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dexperiment.configuration.name=rosselfieldkit
  - mvn clean install -Dgwt.validateOnly -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dexperiment.configuration.name=multiparticipant
  - mvn clean install -Dgwt.validateOnly -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dexperiment.configuration.name=sentences_rating_task
  - mvn clean install -Dgwt.validateOnly -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dexperiment.configuration.name=french_audio
  - mvn clean install -Dgwt.validateOnly -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dexperiment.configuration.name=nonwacq
  - mvn clean install -Dgwt.validateOnly -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dexperiment.configuration.name=zinnen_afmaken
  - mvn clean install -Dgwt.validateOnly -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dexperiment.configuration.name=antwoordraden
  - mvn clean install -Dgwt.validateOnly -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dexperiment.configuration.name=synquiz2
  - mvn clean install -Dgwt.validateOnly -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dexperiment.configuration.name=alloptions
  - mvn clean install -Dgwt.validateOnly -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dexperiment.configuration.name=invitation_validation_example
  - pwd
  - cd gwt-cordova
  - mvn clean package -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dexperiment.configuration.name=with_stimulus_example -Dexperiment.destinationServer=$serverName -Dexperiment.destinationServerUrl=$serverUrl -Dexperiment.groupsSocketUrl=$groupsSocketUrl -Dexperiment.staticFilesUrl=$staticFilesUrl -Dexperiment.registrationUrl=$serverUrl/registrationUrl/demo_submit.pl
  - mv target/with_stimulus_example-*-SNAPSHOT ../../static
  - cd ../ExperimentDesigner
  # generate the documentation and schema files (css is used as the input directory because we dont want any json files to be present)
  - mvn exec:exec -Dexec.args="-classpath %classpath nl.mpi.tg.eg.experimentdesigner.util.JsonToXml ../../static/css ../../static ../../static" -Dexec.classpathScope=runtime -Dexec.executable=java -DversionCheck.allowSnapshots=true -DversionCheck.buildType=testing -DskipTests=true
  - mkdir ../../static/opus-recorder
  - cd ../../static/opus-recorder
  - wget $serverUrl/with_stimulus_example/opus-recorder/recorder.min.js
  # encoderWorker.min.wasm has not been seens since version 6.2.0 
  #- wget $serverUrl/with_stimulus_example/opus-recorder/encoderWorker.min.wasm
  - wget $serverUrl/with_stimulus_example/opus-recorder/encoderWorker.min.js
  - wget $serverUrl/with_stimulus_example/opus-recorder/decoderWorker.min.wasm
  - wget $serverUrl/with_stimulus_example/opus-recorder/decoderWorker.min.js
  - ls ../../static/opus-recorder
  - mkdir ../../static/webjars
  - mkdir ../../static/webjars/jquery
  - mkdir ../../static/webjars/sockjs-client
  - mkdir ../../static/webjars/stomp-websocket
  - cd ../../static/webjars/jquery
  - wget $serverUrl/with_stimulus_example/webjars/jquery/jquery.min.js
  - cd ../sockjs-client
  - wget $serverUrl/with_stimulus_example/webjars/sockjs-client/sockjs.min.js
  - cd ../stomp-websocket
  - wget $serverUrl/with_stimulus_example/webjars/stomp-websocket/stomp.min.js
  - cd ..
  - ls ../../static
  - ls ../../static/*
  
deploy:
  # deploy the documentation and schema files 
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: ../static
  on:
    branch: master