language: java
jdk:
  - oraclejdk8
#cache:
#  directories:
#    these take as long to download from the cache as from the original source
#  - $HOME/.m2
install:
  - mvn install -Dgwt.validateOnly -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn clean test -B -V -Duser.timezone=CET
  - mvn clean install -Dgwt.validateOnly -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dexperiment.configuration.name=multiparticipant
  - mvn clean install -Dgwt.validateOnly -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dexperiment.configuration.name=sentences_rating_task
  - mvn clean install -Dgwt.validateOnly -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dexperiment.configuration.name=french_audio
  - mvn clean install -Dgwt.validateOnly -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dexperiment.configuration.name=nonwacq
  - mvn clean install -Dgwt.validateOnly -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dexperiment.configuration.name=zinnen_afmaken
  - mvn clean install -Dgwt.validateOnly -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dexperiment.configuration.name=antwoordraden
  - mvn clean install -Dgwt.validateOnly -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dexperiment.configuration.name=synquiz2
  - mvn clean install -Dgwt.validateOnly -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dexperiment.configuration.name=alloptions
  
  # generate the documentation and schema files 
  - mvn exec:exec -classpath %classpath nl.mpi.tg.eg.experimentdesigner.util.JsonToXml ../static ../static
  - ls ../static
  
deploy:
  # deploy the documentation and schema files 
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: ../static
  on:
    branch: master