language: java
jdk:
  - oraclejdk8
#cache:
#  directories:
#    these take as long to download from the cache as from the original source
#  - $HOME/.m2
install:
  - mvn install -Dgwt.validateOnly -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn clean test -B -V -Duser.timezone=CET
  - mvn clean install -Dgwt.validateOnly -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dexperiment.configuration.name=multiparticipant
  - mvn clean install -Dgwt.validateOnly -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dexperiment.configuration.name=sentences_rating_task
  - mvn clean install -Dgwt.validateOnly -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dexperiment.configuration.name=french_audio
  - mvn clean install -Dgwt.validateOnly -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dexperiment.configuration.name=nonwacq
  - mvn clean install -Dgwt.validateOnly -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dexperiment.configuration.name=zinnen_afmaken
  - mvn clean install -Dgwt.validateOnly -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dexperiment.configuration.name=antwoordraden
  - mvn clean install -Dgwt.validateOnly -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dexperiment.configuration.name=synquiz2
  - mvn clean install -Dgwt.validateOnly -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dexperiment.configuration.name=alloptions
  - pwd
  - cd gwt-cordova
  - mvn clean package -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dexperiment.configuration.name=with_simulus_example -Dexperiment.destinationServer=$stagingServer -Dexperiment.destinationServerUrl=$stagingServerUrl -Dexperiment.groupsSocketUrl=$stagingGroupsSocketUrl
  - mv target/with_simulus_example-*-SNAPSHOT ../../static
  - wget $serverUrl/with_simulus_example/opus-recorder/recorder.min.js ../../static/opus-recorder/
  - wget $serverUrl/with_simulus_example/opus-recorder/encoderWorker.min.wasm ../../static/opus-recorder/
  - wget $serverUrl/with_simulus_example/opus-recorder/encoderWorker.min.js ../../static/opus-recorder/
  - cd ../ExperimentDesigner
  # generate the documentation and schema files (css is used as the input directory because we dont want any json files to be present)
  - mvn exec:exec -Dexec.args="-classpath %classpath nl.mpi.tg.eg.experimentdesigner.util.JsonToXml ../../static/css ../../static" -Dexec.classpathScope=runtime -Dexec.executable=java -DversionCheck.allowSnapshots=true -DversionCheck.buildType=testing -DskipTests=true
  - ls ../../static
  - ls ../../static/*
  
deploy:
  # deploy the documentation and schema files 
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: ../static
  on:
    branch: master