name: MVN Run Tests and Publish Artifacts
on:
  push:
    #branches-ignore:
    #  - '**' # disables this job
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 30000
        ref: master
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: clean test deploy
      # run: mvn clean test -B -V -Duser.timezone=CET;
      # git rev-list --count --all .;
      # git rev-list --count --all AdaptiveVocabularyAssessmentModule;
      # sed -i '/adaptive-vocabulary-assessment-module/{n;s/-testing-SNAPSHOT/.'$(git rev-list --count --all AdaptiveVocabularyAssessmentModule)'-stable/}' ./AdaptiveVocabularyAssessmentModule/pom.xml;
      run: pwd;
            mvn clean test deploy -DaltDeploymentRepository=snapshot-repo::default::file:../snapshots;
            git status;
            ls -l;
            sed -i 's|<versionCheck.buildType>testing</versionCheck.buildType>|<versionCheck.buildType>stable</versionCheck.buildType>|g' ./pom.xml;
            sed -i 's|-testing-SNAPSHOT|-stable-SNAPSHOT|g' ./pom.xml ./*/pom.xml;           
            mvn clean test deploy -DaltDeploymentRepository=snapshot-repo::default::file:../snapshots;
            sed -i 's|<versionCheck.allowSnapshots>true</versionCheck.allowSnapshots>|<versionCheck.allowSnapshots>false</versionCheck.allowSnapshots>|g' ./pom.xml
            git rev-list --count --all AdaptiveVocabularyAssessmentModule;
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ../snapshots
        keep_files: true
