name: repository-sync
on: 
  push
jobs:
  build:
    runs-on: ubuntu-latest
    environment: repository-sync
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: ''
    - run: pwd; ls -l; git push https://${{ secrets.access_token_name }}:${{ secrets.access_token }}@${{ secrets.mirror_destination }}
        