on:
  push:
    branches:
      - *
environment: repository-sync
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        git push ${{ secrets.mirror_destination }}
      with:
        token: ${{ secrets.access_token }}
        