name: repository-sync
on: 
  push
jobs:
  build:
    runs-on: ubuntu-latest
    environment: repository-sync
    steps:
    # - uses: actions/checkout@v3
      # with:
        # fetch-depth: 0
    - run: git clone https://github.com/MPI-ExperimentGroup/AdaptiveVocabularyAssessmentModule.git; cd AdaptiveVocabularyAssessmentModule; pwd; ls -l; git push https://${{ secrets.access_token_name }}:${{ secrets.access_token }}@${{ secrets.mirror_destination }}
        